//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demo_exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demo_exam()
        {
            this.Chief_experts = new HashSet<Chief_experts>();
            this.Line_experts = new HashSet<Line_experts>();
            this.Members = new HashSet<Members>();
            this.techical_experts = new HashSet<techical_experts>();
        }
    
        public int ID_EXAM { get; set; }
        public int id_WSR { get; set; }
        public string Компетенция { get; set; }
        public Nullable<System.DateTime> Дата_проведения { get; set; }
        public Nullable<int> Кол_во_участников { get; set; }
        public Nullable<int> Кол_во_линейных { get; set; }
        public Nullable<int> Кол_вотехнических { get; set; }
        public Nullable<int> Кол_во_главных { get; set; }
        public string ЦПДЭ { get; set; }
        public string Учреждение { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chief_experts> Chief_experts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Line_experts> Line_experts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Members> Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<techical_experts> techical_experts { get; set; }
    }
}
